apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: multi-tier
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/mearvi/gitops-labs.git
    targetRevision: main
    path: helm/multi-tier-chart

    helm:
      valueFiles:
        - ../../environments/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: multi-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
